package edu.neumont.csc150.model.projectiles;

import edu.neumont.csc150.service.CollisionService;
import edu.neumont.csc150.service.ConfigService;
import edu.neumont.csc150.service.Injectable;

import java.util.LinkedHashSet;
import java.util.Set;

public class ProjectileManager {
    private static final Set<Projectile> projectiles = new LinkedHashSet<>();
    static CollisionService collisionService;
    static ConfigService configService;

    public ProjectileManager(Injectable collision, Injectable config) {
        collisionService = (CollisionService) collision;
        configService = (ConfigService) config;
    }

    public void update() {
        // snapshot improvement generated by ChatGPT-4o
        Set<Projectile> snapshot;
        synchronized (projectiles) {
            snapshot = new LinkedHashSet<>(projectiles);
        }

        for (Projectile b : snapshot)
            b.action();
    }

    static void add(Projectile proj) {
        synchronized (projectiles) {
            projectiles.add(proj);
        }
    }

    static void remove(Projectile proj) {
        synchronized (projectiles) {
            projectiles.remove(proj);
            collisionService.removeHitBox(proj.getCollider());
        }
    }
}
